(6-2)中級 従業員曖昧検索
tugukurechan-organization/ex-emp-management-bugfix pull request #13
Opened 2024-06-10 03:53 UTC by tugukurechan

(6-2)中級 従業員曖昧検索
の修正をしました。確認おねがいします。

### <修正内容>
* 名前であいまい検索する機能を追加
* デザインを追加

2024-06-10 06:32 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2024-06-10 06:32 UTC, igamasayuki commented on src/main/java/com/example/controller/EmployeeController.java
>  }
・今後の改修や機能追加を楽にするために、Controllerにおいて一覧表示を行うshowListメソッドと、曖昧検索を行うメソッドを統合しましょう。showListメソッド一つだけにするという意味です。

2024-06-10 07:38 UTC, tugukurechan commented
Controllerにおいて一覧表示を行うshowListメソッドと、曖昧検索を行うメソッドを統合しました。確認お願いします。

2024-06-11 00:48 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2024-06-11 00:48 UTC, merged