(5-3)上級 パスワード暗号orハッシュ化
tugukurechan-organization/ex-emp-management-bugfix pull request #14
Opened 2024-06-10 06:29 UTC by tugukurechan

(5-3)上級 パスワード暗号orハッシュ化
を修正しました。確認お願いします。

2024-06-10 06:38 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2024-06-10 06:38 UTC, igamasayuki commented on src/main/java/com/example/repository/AdministratorRepository.java
> +		String hashedPassword = passwordEncoder.encode(password);
これは意味ないので消しましょう。

2024-06-10 06:38 UTC, igamasayuki commented on src/main/java/com/example/repository/AdministratorRepository.java
> +		System.out.println("findby:"+hashedPassword);
これは意味ないので消しましょう。

2024-06-10 06:38 UTC, igamasayuki commented on src/main/java/com/example/repository/AdministratorRepository.java
> +		}
このような処理はサービスに書きましょう。

2024-06-10 06:38 UTC, igamasayuki commented on src/main/java/com/example/repository/AdministratorRepository.java
> +		administrator.setPassword(hashedPassword);
このような処理はサービスに書きましょう。

2024-06-10 06:38 UTC, igamasayuki commented on src/main/java/com/example/repository/AdministratorRepository.java
> +		System.out.println("insert:"+hashedPassword);
消しましょう

2024-06-11 00:46 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2024-06-11 00:46 UTC, igamasayuki commented on src/main/java/com/example/repository/AdministratorRepository.java
> +		if (administratorList.isEmpty()) {
このメソッドですが以下のように修正してください。
・名前をfindByMailAddressに
・引数からパスワードの受け取りをなくす
・JavaDocコメントの更新

2024-06-11 02:37 UTC, tugukurechan commented
途中でshowLIstの修正もしてしまいましたが、5-3を修正しました
### 修正内容
* Javadocコメントの更新
* searchByMailAddressAndPasswordメソッドでパスワードを引数にとる必要がないため、すでにadministratorRepositoryクラスのfindByMailAddressメソッドに統合した。

2024-06-11 02:43 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2024-06-11 02:43 UTC, merged