(1-2)初級 入力値エラー処理
tugukurechan-organization/ex-emp-management-bugfix pull request #2
Opened 2024-06-06 07:25 UTC by tugukurechan

(1-2)初級 入力値エラー処理
を修正しました。確認お願いします。

2024-06-06 08:38 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2024-06-06 08:38 UTC, igamasayuki commented on src/main/java/com/example/form/LoginForm.java
> +	@NotBlank(message = "パスワードは必須です")
ログインフォームに関しては入力値チェックは必要ありません。

2024-06-06 08:54 UTC, tugukurechan commented
修正しました。確認お願いします。

2024-06-07 05:05 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2024-06-07 05:05 UTC, merged