(1-3)中級 email重複チェック
tugukurechan-organization/ex-emp-management-bugfix pull request #6
Opened 2024-06-07 07:16 UTC by tugukurechan

(1-3)中級 email重複チェック
を修正しました。確認お願いします。

2024-06-07 07:57 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2024-06-07 07:57 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +        }
処理自体は問題ありませんが、
if (result.hasErrors()) {
 return toInsert();
}
この処理が上に書かれていると、入力値エラーが全部解消した後に、メールアドレス重複チェックのエラー(or パスワード不一致のエラー)が出ることになるため、全部のエラーメッセージが同時に出るように改修をお願いします。

意味がわからない場合はご相談いただくか、終わっている人に聞いてみてください。

2024-06-07 07:57 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +			model.addAttribute("mailError","そのメールアドレスは使用されています");
　今回のエラーメッセージの登録ですが、
　model.addAttribute("キー", "エラーメッセージ");
　ではなく、resultにエラーメッセージを追加することができます。
　このようにすると、viewでは
　「○○を入力してください」
　というformのvalidateエラーが出る箇所に、今回のものと共通でエラーメッセージを出すことができます。
　BindingResultのAPIマニュアルを見ながら探してみてください。

2024-06-10 00:18 UTC, tugukurechan commented
エラーをmodelに入れるのではなく、まとめてvalidationと表示するように修正しました。確認お願いします。

2024-06-10 01:45 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2024-06-10 01:45 UTC, merged